"""
Django settings for flood_system project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ================= SECURITY =================
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-uekro)-bfq=hv5n5k@9-nmeb&#%^t)!q6ss=0vbjcn&f$l=u8q'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# ================= APPLICATION DEFINITION =================
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'prediction',  # Your main app
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'flood_system.urls'

# ================= TEMPLATES =================
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',  # Main templates directory for combined HTML files
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
            ],
        },
    },
]

WSGI_APPLICATION = 'flood_system.wsgi.application'


# ================= DATABASE =================
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# ================= PASSWORD VALIDATION =================
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ================= INTERNATIONALIZATION =================
# Default language
LANGUAGE_CODE = 'en-us'

# Available languages for the site
LANGUAGES = [
    ('en', 'English'),
    ('sw', 'Kiswahili'),
]

# Path for locale files (where translations are stored)
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

TIME_ZONE = 'Africa/Dar_es_Salaam'

USE_I18N = True
USE_L10N = True
USE_TZ = True


# ================= STATIC FILES =================
STATIC_URL = '/static/'

# Directories where Django will look for static files during development
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Directory where collectstatic will gather static files for production
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Static files finders
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]


# ================= MEDIA FILES =================
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# ================= LOGIN/REDIRECTS =================
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'home'


# ================= SESSION SETTINGS =================
SESSION_COOKIE_AGE = 86400  # 24 hours in seconds
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'


# ================= EMAIL SETTINGS =================
# For development - emails will be printed to console (no actual sending)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# For production with Gmail (uncomment and configure):
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'your-email@gmail.com'
# EMAIL_HOST_PASSWORD = 'your-app-password'  # Use App Password

# For production with SendGrid:
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.sendgrid.net'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'apikey'
# EMAIL_HOST_PASSWORD = 'your-sendgrid-api-key'

# Default from email address
DEFAULT_FROM_EMAIL = 'FloodGuard Tanzania <noreply@floodguard.com>'

# Admin email addresses to receive alerts
ADMIN_EMAILS = [
    # 'admin@example.com',
    # 'your-email@gmail.com',
]


# ================= SMS SETTINGS =================
# Using Africa's Talking (recommended for Tanzania)
# Sign up at https://africastalking.com/ to get API keys

# Africa's Talking Configuration
AFRICASTALKING_USERNAME = 'sandbox'  # Use 'sandbox' for testing
AFRICASTALKING_API_KEY = ''  # Get from Africa's Talking dashboard
AFRICASTALKING_SENDER_ID = 'FloodGuard'  # Sender ID (max 11 characters)

# For testing SMS without API (prints to console)
SMS_DEBUG_MODE = True  # Set to False for production

# Phone numbers for SMS alerts (add admin phone numbers here)
ADMIN_PHONE_NUMBERS = [
    # '255700000000',  # Tanzania format: 255XXXXXXXXX
    # '255712345678',
]


# ================= TELEGRAM SETTINGS =================
# Alternative to SMS - Create a bot via @BotFather on Telegram
TELEGRAM_BOT_TOKEN = ''  # Get from @BotFather
TELEGRAM_CHAT_ID = ''  # Your chat ID (get from @userinfobot)


# ================= ALERT THRESHOLDS =================
# Minimum risk level to send alerts ('Low', 'Moderate', 'High')
ALERT_THRESHOLD = 'Moderate'  # Send alerts for Moderate and above

# Cooldown between alerts for same region (in seconds)
ALERT_COOLDOWN_SECONDS = 3600  # 1 hour


# ================= DEFAULT AUTO FIELD =================
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ================= LOGGING =================
# For tracking alerts and errors
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'alerts.log',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        'prediction': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}


# ================= CSRF SETTINGS =================
CSRF_COOKIE_SECURE = False  # Set to True in production with HTTPS
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_TRUSTED_ORIGINS = []  # Add your production domains here


# ================= SECURITY SETTINGS =================
# HSTS Settings (enable in production)
SECURE_HSTS_SECONDS = 0  # Set to 31536000 in production
SECURE_HSTS_INCLUDE_SUBDOMAINS = False
SECURE_HSTS_PRELOAD = False

# SSL Settings (enable in production)
SECURE_SSL_REDIRECT = False
SECURE_PROXY_SSL_HEADER = None
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True

# Referrer Policy
SECURE_REFERRER_POLICY = 'same-origin'

# X-Frame Options
X_FRAME_OPTIONS = 'DENY'


# ================= STATIC AND MEDIA URLS =================
# For development - Django will serve static files
# For production, use collectstatic and configure your web server